### ISSUE TITLE
Add Secret Sync Operator to OperatorHub.io

### ISSUE THREAD

**Issue by ron1** [IBM-Cloud/kube-samples#46]
Add Secret Sync Operator to OperatorHub.io at https://github.com/operator-framework/community-operators.

**Comment by jpapejr** [comment]
I'll take a look at the steps needed to do this..

**Comment by jpapejr** [comment]
Pushing this [example] operator to operatorhub.io requires some assertions regarding the publishing entity. In this case, I'm hesitant to list IBM Cloud as the entity since this is not a supported project, just an example operator (as indicated in the readme). Second, I'm not finding any other operators in the 'hub that are for this type of utility usage instead of a managed stateful application. So there's that... Lastly, and given the previous two items, we'd need to find an approved operator image repo on dockerhub or something similar to distribute the operator on the 'hub for users to leverage. Given the approvals and requirements for doing that, I'm not sure it's worth it at this time... 

I'm going to chalk this one up as `won't fix` for now but I'm not against revisiting it at a later date.

**Comment by cameronbraid** [comment]
Found an alternative which is easy to install

https://appscode.com/products/kubed/v0.12.0-rc.2/guides/config-syncer/intra-cluster/

**Comment by jpapejr** [comment]
@cameronbraid Nice find.. I'll have to give that a shot.
